# Generated by Django 4.1.1 on 2022-09-11 05:34

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_alter_category_slug_alter_countrypage_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('address', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('website', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('rating', models.CharField(blank=True, max_length=255, null=True)),
                ('reviews', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_image', models.ImageField(upload_to='uploads')),
                ('timing', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listing.statepage')),
            ],
        ),
    ]
