# Generated by Django 4.1.1 on 2022-09-11 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0007_alter_businessdetails_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='state',
        ),
    ]
