# Generated by Django 4.1.1 on 2022-09-11 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0011_remove_businessdetails_business_city_delete_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessdetails',
            name='address',
        ),
        migrations.RemoveField(
            model_name='businessdetails',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='businessdetails',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='businessdetails',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='businessdetails',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='businessdetails',
            name='timing',
        ),
        migrations.RemoveField(
            model_name='businessdetails',
            name='website',
        ),
    ]
