# Generated by Django 4.1.1 on 2022-09-11 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0012_remove_businessdetails_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessDetails',
        ),
    ]
