# Generated by Django 4.1.1 on 2022-09-11 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0013_delete_businessdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CountryPage',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.DeleteModel(
            name='StatePage',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
