# Generated by Django 4.1.1 on 2022-09-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0015_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog'),
        ),
    ]
