# Generated by Django 4.1.1 on 2022-09-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0017_businessdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessdetails',
            name='stateName',
        ),
        migrations.AddField(
            model_name='statepage',
            name='stateImage',
            field=models.ImageField(default=1, upload_to='state'),
            preserve_default=False,
        ),
    ]
