# Generated by Django 4.1.1 on 2022-09-12 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0018_remove_businessdetails_statename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetails',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listing.statepage'),
        ),
        migrations.AlterField(
            model_name='statepage',
            name='stateImage',
            field=models.ImageField(blank=True, null=True, upload_to='state'),
        ),
    ]
