# Generated by Django 4.1.1 on 2022-09-12 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0019_businessdetails_state_alter_statepage_stateimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetails',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='listing.countrypage'),
        ),
    ]
