# Generated by Django 4.1.1 on 2022-09-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0020_businessdetails_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddListingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=255)),
                ('lName', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField(max_length=1200)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
