# Generated by Django 4.1.1 on 2022-09-12 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0021_addlistingrequest_contactus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='fName',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='lName',
        ),
    ]
