# Generated by Django 4.1.1 on 2022-09-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0022_rename_fname_contactus_name_remove_contactus_lname'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='monday',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
