# Generated by Django 4.1.1 on 2022-09-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0024_statepage_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='addlistingrequest',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addlistingrequest',
            name='clinicName',
            field=models.CharField(default=' ', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addlistingrequest',
            name='clinicTiming',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addlistingrequest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addlistingrequest',
            name='email',
            field=models.CharField(default=' ', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addlistingrequest',
            name='image',
            field=models.ImageField(default=' ', upload_to='addListing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addlistingrequest',
            name='ownerName',
            field=models.CharField(default=' ', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addlistingrequest',
            name='phone',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addlistingrequest',
            name='website',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
