# Generated by Django 4.1.1 on 2022-09-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0025_addlistingrequest_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addlistingrequest',
            name='city',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addlistingrequest',
            name='state',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
