# Generated by Django 4.1.1 on 2022-09-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0026_addlistingrequest_city_addlistingrequest_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addlistingrequest',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='addlistingrequest',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
