# Generated by Django 4.1.1 on 2022-09-15 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0027_alter_addlistingrequest_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetails',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state', to='listing.statepage'),
        ),
    ]
