# Generated by Django 4.1.1 on 2022-09-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0028_alter_businessdetails_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadsForClinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinicName', models.CharField(blank=True, max_length=255, null=True)),
                ('clientName', models.CharField(blank=True, max_length=255, null=True)),
                ('clientPhone', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
