# Generated by Django 4.1.1 on 2022-09-18 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0030_alter_businessdetails_title_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetails',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET, to='listing.city'),
        ),
    ]
