# Generated by Django 4.1.1 on 2022-09-18 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0031_businessdetails_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='time',
            new_name='date',
        ),
    ]
