# Generated by Django 4.1.1 on 2022-09-25 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0033_businessdetails_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessdetails',
            name='timing',
        ),
        migrations.AddField(
            model_name='leadsforclinic',
            name='AppointmentDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
